### ISSUE TITLE
TimezoneActions incorrect return.

### ISSUE THREAD

**Issue by TeunvandenBroek** [teun25/C-sharp-clipboardquestionanswer-#8]
in time zone actions when I copy a country that returns the time zone id instead of the local time

**Comment by RyanThiele** [comment]
Needs more info. What data is incorrect. What data is correct?

**Comment by TeunvandenBroek** [comment]
if i copy for example a country like `nederland` the notification gives now the timezone id as return i want the local time of that country we need to use 1 paramter specific for the class timezoneactions to make this work properly i think

**Comment by TeunvandenBroek** [comment]
example if I copy `nederland` it must give 15:50 (the correct local time) as a return example if I copy `nederland` it should give 15:50 as return and not the time zone id
