### ISSUE TITLE
Incorrect return in TimespanActions.cs

### ISSUE THREAD

**Issue by TeunvandenBroek** [teun25/C-sharp-clipboardquestionanswer-#9]
in timespanactions it immediately gives a return if, for example, I copy 15-11-2019 while it must return the days in between 2 dates.

**Comment by RyanThiele** [comment]
Math was running after the date action and performing math on the date:
  15
  11
- 2019
--------------
-2015

**Comment by RyanThiele** [comment]
Should be corrected in #18
